version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: zencoder_postgres_container
    environment:
      POSTGRES_DB: zencoder_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: